-- Esquema base del SGM: roles, usuarios, permisos y deudas.
-- Postgres corre los scripts de db/init/ en el primer arranque del docker-compose y el CI los
-- aplica antes de los tests: las apps no crean tablas. Las entidades User, Role, Permission y
-- Debt mapean estas tablas tal cual.
-- Es un estado base: el ticket que necesite otro atributo lo cambia aca, en su PR. No hay
-- migraciones: la base se recrea desde db/init/ con docker compose down -v.

-- pgcrypto aporta crypt(), con la que el login verifica las contrasenas BCrypt de users.
CREATE EXTENSION pgcrypto;

-- Cargo del usuario. Es descriptivo y viaja en la cookie de sesion (TPS-13): el acceso a los
-- modulos se decide por permisos, no por rol.
CREATE TABLE roles (
    id   BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(30) NOT NULL UNIQUE
);

-- Usuarios del SGM. El seed inserta primero al usuario de soporte: el paso 1 de la cadena
-- depende de ese orden.
CREATE TABLE users (
    id            BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      VARCHAR(50)  NOT NULL UNIQUE,
    -- Hash BCrypt, como el de las cuentas tecnicas. La verificacion del login (TPS-14) lo
    -- compara dentro de la consulta con crypt() de pgcrypto.
    password_hash VARCHAR(100) NOT NULL,
    role_id       BIGINT       NOT NULL REFERENCES roles (id)
);

-- Catalogo de permisos: uno por modulo con gating (ADMINISTRACION, TESORERIA, AUDITORIA).
CREATE TABLE permissions (
    id   BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(30) NOT NULL UNIQUE
);

CREATE TABLE user_permissions (
    user_id       BIGINT NOT NULL REFERENCES users (id),
    permission_id BIGINT NOT NULL REFERENCES permissions (id),
    PRIMARY KEY (user_id, permission_id)
);

-- Deudas por CUIT (11 digitos, sin guiones, como el cuit del evento de auditoria).
CREATE TABLE debts (
    id     BIGINT         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cuit   VARCHAR(11)    NOT NULL,
    amount NUMERIC(12, 2) NOT NULL CHECK (amount >= 0),
    status VARCHAR(20)    NOT NULL CHECK (status IN ('PENDING', 'FORGIVEN'))
);
