-- Esquema del modulo interno de mensajeria del monolito.
-- Postgres corre los scripts de db/init/ en el primer arranque del docker-compose y el CI los
-- aplica antes de los tests: las apps no crean tablas.

-- Cuentas tecnicas del modulo. Las filas las carga el seed.
CREATE TABLE technical_accounts (
    id            BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      VARCHAR(50)  NOT NULL UNIQUE,
    password_hash VARCHAR(100) NOT NULL,
    role          VARCHAR(10)  NOT NULL CHECK (role IN ('READ', 'WRITE')),
    service_id    VARCHAR(30)  NOT NULL
);

-- Fuente de verdad de los eventos de auditoria: la cola solo los transporta hasta Auditoria.
CREATE TABLE pending_events (
    id          UUID        PRIMARY KEY,
    type        VARCHAR(50) NOT NULL,
    cuit        VARCHAR(11) NOT NULL,
    occurred_at TIMESTAMPTZ NOT NULL,
    status      VARCHAR(20) NOT NULL
);
